name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  Deploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Build & Deploy
        run: echo "Buildings and Deploying Application"
    