name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  TestDeploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Testing of Deploy
        run: echo "Buildings and Deploying Application"
    
  Deploy-Ec2: 
    name: CD to EC2
    needs: TestDeploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checKout@v4        
      - name: Deploy To Server  
        uses: easingthemes/ssh-deploy@v2.2.11
        env: 
          ARGS: "-rltgoDzvO -i"
          SSH_HOST: ${{secrets.SSH_HOST}}
          PRIVATE_KEY: ${{secrets.SSH_KEY_PEM}}
          SSH_USER: ${{secrets.SSH_USER}}
          TARGET: /var/www/html/vue-remember-01
        