name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  Deploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest
    name: Showing current step
    script: echo 'Preparando o Deploy para Máquina EC2'