name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  TestDeploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Testing of Deploy
        run: echo "Buildings and Deploying Application"
    
  Deploy-Ec2: 
    name: CD to EC2
    needs: TestDeploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checKout@v4        
      - name: Deploy To Server  
        uses: appleboy/ssh-action@master
        with:           
          key: ${{secrets.SSH_KEY_PEM}}
          host: ${{secrets.SSH_HOST}}          
          username: ${{secrets.SSH_USER}}
          scripts: | 
            echo "Hello World!!!"
        