name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  TestDeploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Testing of Deploy
        run: echo "Buildings and Deploying Application"
    
  Deploy-Ec2: 
    name: CD to EC2
    needs: TestDeploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checKout@v4        
      - name: Deploy To Server  
        uses: easingthemes/ssh-deploy@v3
        with: 
          ARGS: "-rltgoDzvO -i"
          ssh-private-key: ${{secrets.SSH_KEY_PEM}}
          remote-host: ${{secrets.SSH_HOST}}          
          remote-user: ${{secrets.SSH_USER}}
          target: /var/www/html/vue-remember-01
        